Initial commit
Arborym/Pax-Academia pull request #161
Opened 2023-04-10 20:02 UTC by Arborym

2023-04-15 21:53 UTC, Arborym commented
Ignore build failure

2023-04-17 18:41 UTC, sebastiaan-daniels commented
Have we spoken to the folks over @ CopyLeaks for a potential free (sponsored) API key?
Might be best to do that before merging a scraper that tries to bypass multiple anti-bot measures.

2023-04-27 09:48 UTC, sebastiaan-daniels requested changes

2023-04-27 09:48 UTC, sebastiaan-daniels commented on cogs/DetectAI.py
> -    )
Re-add staff only functionality of the command as discussed here:
https://discord.com/channels/238956364729155585/1040360228388098159/1099443748871610470

2023-04-27 17:15 UTC, sebastiaan-daniels approved these changes

2023-04-28 23:38 UTC, merged