created new documentation for cogs and utils
Arborym/Pax-Academia pull request #214
Opened 2023-08-06 19:13 UTC by dddictionary

I changed the way the docs are written. 
The documentation for each cog is formatted like so:
- Commands implemented:
    - `command`
- Description:
    - Description

If I have missed any functionalities in certain cogs or utils, please let me know and I will update them accordingly.

2023-08-10 19:02 UTC, sebastiaan-daniels requested changes

2023-08-10 19:02 UTC, sebastiaan-daniels commented on cogs/README.md
> +  - Used to search chemsitry databases for compunds.
Chemistry | compounds

2023-08-11 05:04 UTC, sebastiaan-daniels approved these changes

2023-08-12 22:18 UTC, Arborym approved these changes

2023-08-14 14:10 UTC, merged